package ua.goit.gojava.servicePackage;


public enum ElementType {
    INT, DOUBLE, NUMBER, OPERATOR, PARENTHESIS, PLUS, MINUS, DIVIDE, MULTIPLY, EQUALLY, OPEN_PARENTHESIS, CLOSE_PARENTHESIS, ERROR
}
